### ISSUE TITLE
main is broken: sandbox::mcp references nonexistent policy::CapabilityV1::Sandbox* variants

### ISSUE THREAD

**Issue by bannff** [bannff/Rust-Factory#52]
## Problem

After merging PR #51 (sandbox Docker CLI lifecycle brick, closing #40), `main` at f038cac fails to compile with --all-features:

```
error[E0599]: no variant or associated item named `SandboxStart` found for enum `CapabilityV1`
error[E0599]: no variant or associated item named `SandboxExecute` found for enum `CapabilityV1`
error[E0599]: no variant or associated item named `SandboxStatus` found for enum `CapabilityV1`
error[E0599]: no variant or associated item named `SandboxStop` found for enum `CapabilityV1`
  --> crates/sandbox/src/mcp.rs
```

`crates/sandbox/src/mcp.rs` calls `self.authorize(CapabilityV1::SandboxStart)` etc., but `crates/policy/src/lib.rs::CapabilityV1` has no Sandbox* variants — only Agent*/Workflow*/Evaluation*/Observability*/Memory* exist. This means `cargo check --workspace --all-features` and `cargo clippy -p sandbox --features mcp` currently fail on main.

Reproduced independently on a clean checkout of main (f038cac), confirmed via `git stash` isolation — not caused by any concurrent branch's changes.

## Fix

Add `SandboxStart`, `SandboxExecute`, `SandboxStatus`, `SandboxStop` variants to `policy::CapabilityV1` (plus their `as_str` arms and any exhaustive match sites), matching the naming convention of existing variants. Needs the standard gate: rust-factory-sme design review (policy is a shared capability enum every brick depends on), implementation, QA, security, final architecture, then `make check`.

## Impact

Blocks `make check` for any workspace-wide command with `--all-features`. The Makefile's `lint-features`/`test-features` targets check `sandbox` per-feature (`--features docker`, `--features mcp`, `--features docker,mcp`) rather than `--all-features`, so the individual Makefile targets may still pass depending on feature unification — needs verification once fixed.

**Comment by bannff** [comment]
Design gate (rust-factory-sme) found a second, independent break from the same PR #51 merge: scripts/validate_brick_registry.py::STATUS_ONLY_FAMILIES still lists sandbox as status-only/core, but crates/sandbox/Cargo.toml now correctly declares role="brick", status="migration-pending". python3 scripts/validate_brick_registry.py fails independently of the CapabilityV1 compile error.

Fix plan (both required for make check to go green):
1. policy::CapabilityV1 - add SandboxStart/SandboxExecute/SandboxStatus/SandboxStop variants + as_str arms, matching existing naming. No exhaustive-match sites elsewhere need touching (confirmed).
2. scripts/validate_brick_registry.py - remove "sandbox" from STATUS_ONLY_FAMILIES (a stale entry now that PR #51 promoted sandbox out of status-only, not a new package registration - treating this narrow removal as the required correction rather than a new-package setup action).
3. .kiro/specs/policy/requirements.md req 3's closed capability list should mention the 4 new Sandbox variants since the spec calls it a permanent wire commitment.
